[package]
name = "ball"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_egui = "0.30"
csv = "1.3.0"
plotters = "0.3.7"
bevy_editor_pls = "0.10.0"
bevy-inspector-egui = "0.27.0"
plotters-backend = "0.3.7"
instant = { version = "0.1.13", features = ["wasm-bindgen"] }

