[package]
name = "ball"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_egui = "0.30"
bevy-inspector-egui = "0.27.0"
egui_plot = "0.29.0"
csv = "1.3.0"
plotters = "0.3.7"
plotters-backend = "0.3.7"
